In [4]:
import jax
import jax.numpy as jnp
print("Using jax", jax.__version__)

Using jax 0.6.2


In [5]:
a = jnp.zeros((2, 5), dtype=jnp.float32)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
b = jnp.arange(6)
print(b)

[0 1 2 3 4 5]


In [7]:
b.__class__

jaxlib._jax.ArrayImpl

In [12]:
b.device

CpuDevice(id=0)

In [9]:
b_cpu = jax.device_get(b)
print(b_cpu.__class__)

<class 'numpy.ndarray'>


In [14]:
b_gpu = jax.device_put(b_cpu)
print(f'Device put: {b_gpu.__class__} on {b_gpu.device}')

Device put: <class 'jaxlib._jax.ArrayImpl'> on TFRT_CPU_0


In [11]:
b_cpu + b_gpu

Array([ 0,  2,  4,  6,  8, 10], dtype=int32)

In [ ]:
jax.devices()

[CpuDevice(id=0)]