In [4]:
import jax
import jax.numpy as jnp
print("Using jax", jax.__version__)

Using jax 0.6.2


In [5]:
a = jnp.zeros((2, 5), dtype=jnp.float32)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
b = jnp.arange(6)
print(b)

[0 1 2 3 4 5]


In [7]:
b.__class__

jaxlib._jax.ArrayImpl

In [12]:
b.device

CpuDevice(id=0)

In [9]:
b_cpu = jax.device_get(b)
print(b_cpu.__class__)

<class 'numpy.ndarray'>


In [14]:
b_gpu = jax.device_put(b_cpu)
print(f'Device put: {b_gpu.__class__} on {b_gpu.device}')

Device put: <class 'jaxlib._jax.ArrayImpl'> on TFRT_CPU_0


In [11]:
b_cpu + b_gpu

Array([ 0,  2,  4,  6,  8, 10], dtype=int32)

In [ ]:
jax.devices()

[CpuDevice(id=0)]

In [ ]:
b_new = b.at[0].set(1)
print('Original array:', b)
print('Changed array:', b_new)

In [ ]:
rng = jax.random.PRNGKey(42)

In [ ]:
# A non-desirable way of generating pseudo-random numbers...
jax_random_number_1 = jax.random.normal(rng)
jax_random_number_2 = jax.random.normal(rng)
print('JAX - Random number 1:', jax_random_number_1)
print('JAX - Random number 2:', jax_random_number_2)

# Typical random numbers in NumPy
np.random.seed(42)
np_random_number_1 = np.random.normal()
np_random_number_2 = np.random.normal()
print('NumPy - Random number 1:', np_random_number_1)
print('NumPy - Random number 2:', np_random_number_2)

In [ ]:
rng, subkey1, subkey2 = jax.random.split(rng, num=3)  # We create 3 new keys
jax_random_number_1 = jax.random.normal(subkey1)
jax_random_number_2 = jax.random.normal(subkey2)
print('JAX new - Random number 1:', jax_random_number_1)
print('JAX new - Random number 2:', jax_random_number_2)

In [ ]:
def simple_graph(x):
    x = x + 2
    x = x ** 2
    x = x + 3
    y = x.mean()
    return y

inp = jnp.arange(3, dtype=jnp.float32)
print('Input', inp)
print('Output', simple_graph(inp))

In [ ]:
jax.make_jaxpr(simple_graph)(inp)

In [ ]:
jaxpr ::= { lambda Var* ; Var+.
            let Eqn*
            in  [Expr+] }

In [ ]:
global_list = []

# Invalid function with side-effect
def norm(x):
    global_list.append(x)
    x = x ** 2
    n = x.sum()
    n = jnp.sqrt(n)
    return n

jax.make_jaxpr(norm)(inp)